// Authenticate flow actions
export const AUTH_FLOW_REQUEST = 'AUTH_FLOW_REQUEST';
export const AUTH_FLOW_SUCCESS = 'AUTH_FLOW_SUCCESS';
export const AUTH_FLOW_FAILURE = 'AUTH_FLOW_FAILURE';

export const GET_TOKEN_REQUEST = 'GET_TOKEN_REQUEST';
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS';
export const GET_TOKEN_FAILURE = 'GET_TOKEN_FAILURE';

export const AUTHENTICATE_REQUEST = 'AUTHENTICATE_REQUEST';
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_FAILURE = 'AUTHENTICATE_FAILURE';

// Notifier actions
export const DISPLAY_NOTIFIER = 'DISPLAY_NOTIFIER';
export const RESET_NOTIFIER = 'RESET_NOTIFIER';
export const CLOSE_NOTIFIER = 'CLOSE_NOTIFIER';

// Article ACtions
export const ARTICLES_REQUEST = 'ARTICLES_REQUEST';
export const ARTICLES_SUCCESS = 'ARTICLES_SUCCESS';
export const ARTICLES_FAILURE = 'ARTICLES_FAILURE';